# Generated by Django 5.0.4 on 2024-04-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
