# Generated by Django 5.0.4 on 2024-04-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_base_price_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='cost_price',
        ),
    ]
