# Generated by Django 5.0.4 on 2024-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
