# Generated by Django 5.0.4 on 2024-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('cash', 'cash')], default='paystack', max_length=20),
        ),
    ]
