# Generated by Django 5.0.4 on 2024-05-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_order_transaction_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_completed',
            new_name='is_delivered',
        ),
    ]
