# Generated by Django 5.0.4 on 2024-05-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_rename_transaction_completed_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
